apiVersion: v1
kind: pod
metadata:
  name: my-pod
  generateName: mgenerateName
  namespace: namespace
  labels:
    key1: value1
    key2: value2
  annotations:
    key1: value1
    key2: value2
spec:
  containers:
    - name: my-container
      image: images
      imagePullPolicy: pullPolicy
      commands: [commands]
      args: [args]
      workDir: workDir
      ports:
        containerPort: 
        hostIP:
        hostPort:
        name:
        protocol:
      env:
        name:
        value:
        valueFrom:
          configMapKeyRef:
            key:
            name:
            optional:
          fieldRef:
          fileKeyRef:
            key:
            path:
            volumeName:
            optional:
          resourceFieldRef:
            resource:
            containerName:
            divisor:
          secretKeyRef:
            key:
            name:
            optional:
      envFrom:
        configMapRef:
          name:
          optional:
        prefix:
        secretRef:
          name:
          optional:
      volumeMounts:
        mountPath:
        name:
        propagation:
        readOnly:
        recursiveReadOnly:
        subPath:
        subPathExpr:
      volumeDevices:
        devicePath:
        name:
      resources:
        claims:
          name:
          request:
        limits:
        requests:
      resizePolicy:
        resourceName:
        restartPolicy:
      lifecycle:
status:
  ..........
